import { Achievement, PlayerSkinId, SkinConfig } from '../types/maze';

export const SKINS: Record<PlayerSkinId, SkinConfig> = {
  classic_orb: {
    id: 'classic_orb',
    name: 'Golden Soul Sphere',
    price: 0,
    icon: '🔮',
    description: 'The standard radiant golden sphere of navigation.',
    trailColor: '#f59e0b',
  },
  cyber_cube: {
    id: 'cyber_cube',
    name: '3D Cyber Matrix Cube',
    price: 150,
    icon: '🧊',
    description: 'Extruded neon holo-cube with digital grid matrix particles.',
    trailColor: '#06b6d4',
  },
  phantom_ghost: {
    id: 'phantom_ghost',
    name: 'Spectral Phantom',
    price: 250,
    icon: '👻',
    description: 'Intangible spirit form that floats through shadowed corridors.',
    trailColor: '#a855f7',
  },
  obsidian_golem: {
    id: 'obsidian_golem',
    name: 'Magma Core Golem',
    price: 400,
    icon: '🔥',
    description: 'Molten volcanic core encased in polished obsidian plating.',
    trailColor: '#ef4444',
  },
  royal_crown: {
    id: 'royal_crown',
    name: 'Imperial Sovereign Crown',
    price: 600,
    icon: '👑',
    description: 'Gilded crown for champions who master extreme mazes.',
    trailColor: '#eab308',
  },
  celestial_star: {
    id: 'celestial_star',
    name: 'Astraea Star Gem',
    price: 1000,
    icon: '⭐',
    description: 'Pure starlight gem emitting cosmic particles as you traverse.',
    trailColor: '#ec4899',
  },
};

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_win',
    title: 'First Vault Cleared',
    description: 'Successfully solve your first maze labyrinth.',
    icon: '🏆',
    rewardCoins: 100,
    progress: 0,
    target: 1,
    completed: false,
    claimed: false,
  },
  {
    id: 'maze_master',
    title: 'Labyrinth Sovereign',
    description: 'Clear 10 maze levels in any difficulty.',
    icon: '👑',
    rewardCoins: 300,
    progress: 0,
    target: 10,
    completed: false,
    claimed: false,
  },
  {
    id: 'coin_collector',
    title: 'Soul Fragment Hoarder',
    description: 'Gather 30 soul fragments from maze corridors.',
    icon: '✧',
    rewardCoins: 200,
    progress: 0,
    target: 30,
    completed: false,
    claimed: false,
  },
  {
    id: 'speed_daemon',
    title: 'Chronos Sprinter',
    description: 'Clear a maze level in under 35 seconds.',
    icon: '⚡',
    rewardCoins: 250,
    progress: 0,
    target: 1,
    completed: false,
    claimed: false,
  },
  {
    id: 'ghost_walker',
    title: 'Spectral Passage',
    description: 'Use Ghost Mode or Wall Pass power-ups 3 times.',
    icon: '👻',
    rewardCoins: 150,
    progress: 0,
    target: 3,
    completed: false,
    claimed: false,
  },
  {
    id: 'ad_supporter',
    title: 'Patron of the Vault',
    description: 'Watch 2 sponsored reward video ads.',
    icon: '🎬',
    rewardCoins: 300,
    progress: 0,
    target: 2,
    completed: false,
    claimed: false,
  },
];
