import { Achievement, PlayerSkinId, SkinConfig, WeaponConfig, WeaponId } from '../types/maze';

export const WEAPONS: Record<WeaponId, WeaponConfig> = {
  tactical_pistol: {
    id: 'tactical_pistol',
    name: 'Tactical Cyber Pistol',
    price: 0,
    damage: 28,
    fireRateMs: 220,
    maxClip: 12,
    reloadTimeMs: 1100,
    icon: '🔫',
    description: 'Standard semi-automatic sidearm with high precision.',
    bulletColor: '#f59e0b',
    soundType: 'pistol',
    isAutomatic: false,
    category: 'pistol',
  },
  ak47_assault: {
    id: 'ak47_assault',
    name: 'AK-47 Tactical Rifle',
    price: 1200,
    damage: 38,
    fireRateMs: 110,
    maxClip: 30,
    reloadTimeMs: 1400,
    icon: '⚔️',
    description: 'Full-automatic assault rifle. Hold fire button for rapid continuous burst.',
    bulletColor: '#eab308',
    soundType: 'ak47',
    isAutomatic: true,
    category: 'rifle',
  },
  shotgun_enforcer: {
    id: 'shotgun_enforcer',
    name: 'Spectre Shotgun Enforcer',
    price: 1800,
    damage: 95,
    fireRateMs: 750,
    maxClip: 6,
    reloadTimeMs: 1900,
    icon: '💥',
    description: 'Heavy double-barrel buckshot blast that annihilates close-range targets.',
    bulletColor: '#ef4444',
    soundType: 'shotgun',
    isAutomatic: false,
    category: 'shotgun',
  },
  plasma_rifle: {
    id: 'plasma_rifle',
    name: 'Hyper Plasma Burst Rifle',
    price: 2500,
    damage: 48,
    fireRateMs: 130,
    maxClip: 35,
    reloadTimeMs: 1500,
    icon: '⚡',
    description: 'Automatic high-tech energy rifle firing supercharged cyan plasma bolts.',
    bulletColor: '#06b6d4',
    soundType: 'plasma',
    isAutomatic: true,
    category: 'rifle',
  },
  grenade_launcher: {
    id: 'grenade_launcher',
    name: 'M32 Explosive Grenade Launcher',
    price: 3800,
    damage: 180,
    fireRateMs: 800,
    maxClip: 4,
    reloadTimeMs: 2200,
    icon: '💣',
    description: 'Launches bouncing explosive grenades that detonate with a massive fire blast.',
    bulletColor: '#f97316',
    soundType: 'grenade',
    isAutomatic: false,
    category: 'explosive',
  },
  rocket_launcher: {
    id: 'rocket_launcher',
    name: 'RPG-7 Void Rocket Launcher',
    price: 5000,
    damage: 300,
    fireRateMs: 1200,
    maxClip: 2,
    reloadTimeMs: 2600,
    icon: '🚀',
    description: 'Heavy rocket launcher firing high-velocity missiles with destructive area blast.',
    bulletColor: '#dc2626',
    soundType: 'rocket',
    isAutomatic: false,
    category: 'explosive',
  },
};

export const SKINS: Record<PlayerSkinId, SkinConfig> = {
  classic_orb: {
    id: 'classic_orb',
    name: 'Golden Soul Sphere',
    price: 0,
    icon: '🔮',
    description: 'The standard radiant golden sphere of navigation.',
    trailColor: '#f59e0b',
  },
  cyber_cube: {
    id: 'cyber_cube',
    name: '3D Cyber Matrix Cube',
    price: 600,
    icon: '🧊',
    description: 'Extruded neon holo-cube with digital grid matrix particles.',
    trailColor: '#06b6d4',
  },
  phantom_ghost: {
    id: 'phantom_ghost',
    name: 'Spectral Phantom',
    price: 1200,
    icon: '👻',
    description: 'Intangible spirit form that floats through shadowed corridors.',
    trailColor: '#a855f7',
  },
  obsidian_golem: {
    id: 'obsidian_golem',
    name: 'Magma Core Golem',
    price: 2000,
    icon: '🔥',
    description: 'Molten volcanic core encased in polished obsidian plating.',
    trailColor: '#ef4444',
  },
  royal_crown: {
    id: 'royal_crown',
    name: 'Imperial Sovereign Crown',
    price: 3500,
    icon: '👑',
    description: 'Gilded crown for champions who master extreme mazes.',
    trailColor: '#eab308',
  },
  celestial_star: {
    id: 'celestial_star',
    name: 'Astraea Star Gem',
    price: 5000,
    icon: '⭐',
    description: 'Pure starlight gem emitting cosmic particles as you traverse.',
    trailColor: '#ec4899',
  },
};

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_win',
    title: 'First Vault Cleared',
    description: 'Successfully solve your first maze labyrinth.',
    icon: '🏆',
    rewardCoins: 100,
    progress: 0,
    target: 1,
    completed: false,
    claimed: false,
  },
  {
    id: 'maze_master',
    title: 'Labyrinth Sovereign',
    description: 'Clear 10 maze levels in any difficulty.',
    icon: '👑',
    rewardCoins: 300,
    progress: 0,
    target: 10,
    completed: false,
    claimed: false,
  },
  {
    id: 'coin_collector',
    title: 'Soul Fragment Hoarder',
    description: 'Gather 30 soul fragments from maze corridors.',
    icon: '✧',
    rewardCoins: 200,
    progress: 0,
    target: 30,
    completed: false,
    claimed: false,
  },
  {
    id: 'speed_daemon',
    title: 'Chronos Sprinter',
    description: 'Clear a maze level in under 35 seconds.',
    icon: '⚡',
    rewardCoins: 250,
    progress: 0,
    target: 1,
    completed: false,
    claimed: false,
  },
  {
    id: 'ghost_walker',
    title: 'Spectral Passage',
    description: 'Use Ghost Mode or Wall Pass power-ups 3 times.',
    icon: '👻',
    rewardCoins: 150,
    progress: 0,
    target: 3,
    completed: false,
    claimed: false,
  },
  {
    id: 'ad_supporter',
    title: 'Patron of the Vault',
    description: 'Watch 2 sponsored reward video ads.',
    icon: '🎬',
    rewardCoins: 300,
    progress: 0,
    target: 2,
    completed: false,
    claimed: false,
  },
  {
    id: 'google_connected',
    title: 'Google Cloud Synchronized',
    description: 'Connect your Google Account to back up progress and earn achievements.',
    icon: '☁️',
    rewardCoins: 250,
    progress: 0,
    target: 1,
    completed: false,
    claimed: false,
  },
  {
    id: 'laser_puzzle_solver',
    title: 'Laser Prism Engineer',
    description: 'Solve a Laser Beam & Mirror deflector puzzle stage.',
    icon: '⚡',
    rewardCoins: 200,
    progress: 0,
    target: 1,
    completed: false,
    claimed: false,
  },
  {
    id: 'ice_slide_master',
    title: 'Glacial Navigator',
    description: 'Master a friction sliding ice block maze stage.',
    icon: '🧊',
    rewardCoins: 200,
    progress: 0,
    target: 1,
    completed: false,
    claimed: false,
  },
  {
    id: 'level_5_master',
    title: 'Saga Pathfinder (Lvl 5)',
    description: 'Reach and complete Level 5 in Campaign Saga Mode.',
    icon: '🌟',
    rewardCoins: 300,
    progress: 0,
    target: 5,
    completed: false,
    claimed: false,
  },
];
